<?php
/**
 * Created by PhpStorm.
 * User: Qulam Alisoy
 * Date: 3/24/2018
 * Time: 10:53 AM
 */

namespace app\controllers;

use app\components\Helpers;
use app\components\ModuleTextBehavior;
use app\components\UserVerifyBehavior;
use app\models\Carousel;
use app\models\Clients;
use app\models\Page;
use app\models\Partners;
use yii;
use yii\easyii\modules\product\models\Product;
use yii\easyii\modules\productcategory\models\ProductCategory;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;
use yii\helpers\VarDumper;
use yii\web\Controller;

class ProductCategoryController extends Controller
{
    public $content_actions = ['index'];

    public function behaviors()
    {
        return [
            ModuleTextBehavior::className(),

            'user-verify' => [
                'class' => UserVerifyBehavior::className(),
                'actions' => ['index'],
            ]
        ];
    }


    /**
     * @param $action
     * @return bool
     * @throws yii\web\BadRequestHttpException
     */
    public function beforeAction($action)
    {
        if (yii::$app->controller->action->id === 'append-category' || yii::$app->controller->action->id === 'append-alt-category') {
            $this->enableCsrfValidation = false;
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @return string
     */
    public function actionIndex()
    {
        $this->view->title = 'Product Category';//Yii translate **
        $clients = Clients::getAllClients();
        $partners = Partners::getPartners();
        $carousel = Carousel::getCarouselByPage(49);
        $productCategories = ProductCategory::getProductCategory(0, null, null, 6);
        $productCategoriesForLink = ProductCategory::getProductCategory(0);
        $productCategory = ProductCategory::getProductCategory();
        $productCategoriesForRightZone = ArrayHelper::map(ProductCategory::getProductCategory(0), 'id', 'title');

        return $this->render('index', [
            'clients' => $clients,
            'partners' => $partners,
            'carousel' => $carousel,
            'productCategories' => $productCategories,
            'page' => $page,
            'productCategory' => $productCategory,
            'productCategoriesForRightZone' => $productCategoriesForRightZone,
            'productCategoriesForLink' => $productCategoriesForLink,
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws yii\web\NotFoundHttpException
     */
    public function actionView($id)
    {
        $this->view->title = 'Product Alt Category';//Yii translate **
        $clients = Clients::getAllClients();
        $partners = Partners::getPartners();
        $carousel = Carousel::getCarouselByCategory($id);
        $productCategories = ProductCategory::getProductCategory(0);
        $productCategory = ProductCategory::getProductCategory(null, $id);
        $altCategories = ProductCategory::getProductCategory($id, null, null, 6);
        $altCategoriesForRightZone = ArrayHelper::map($altCategories, 'id', 'title');

        /*After changed*/
        $id = yii::$app->request->get('id');
        $slug = yii::$app->request->get('slug');

        $products = Product::getProductByParent($id);
        /*After changed*/

        return $this->render('view', [
            'clients' => $clients,
            'partners' => $partners,
            'carousel' => $carousel,
            'productCategories' => $productCategories,
            'altCategories' => $altCategories,
            'productCategory' => $productCategory,
            'altCategoriesForRightZone' => $altCategoriesForRightZone,
            'products' => $products
        ]);
    }

    /**
     * @param $id
     * @return string
     * @throws yii\web\NotFoundHttpException
     */
    public function actionCategoryIn($id)
    {
        $this->view->title = 'Products';//Yii translate **

        $clients = Clients::getAllClients();
        $partners = Partners::getPartners();
        $productCategories = ProductCategory::getProductCategory(0);
        $products = Product::getProductByParent($id);
        $carousel = Carousel::getCarouselByCategory($id);
        $altCategories = ProductCategory::getProductCategory();

        return $this->render('category-in', [
            'clients' => $clients,
            'partners' => $partners,
            'productCategories' => $productCategories,
            'products' => $products,
            'carousel' => $carousel,
            'altCategories' => $altCategories,
        ]);
    }


    /**
     *Append Category When Clicked Load More Pr Button ...
     */
    public function actionAppendCategory()
    {
        if (yii::$app->request->isAjax) {
            $limit = ProductCategory::APPEND_CATEGORY_LIMIT;
            $post = yii::$app->request->post();
            $lastId = $post['lastId'];
            $categories = ProductCategory::getDataForAjax($lastId, $limit, 0);
            $state = true;
            $categoriesIdArr = [];
            $result = [];

            foreach ($categories as $key => $val) {
                $categoriesIdArr[$key] = $val['order_num'];
            }

            function getMinElement($Arr)
            {
                $min = $Arr[0];
                foreach ($Arr as $k => $v) {
                    if ($min > $v) {
                        $min = $v;
                    }
                }
                return $min;
            }

            $minId = getMinElement($categoriesIdArr);
            $reason = ProductCategory::getDataForAjax($minId, $limit);

            if (count($reason) == 0) {
                $state = false;
            }

            $output = '';

            foreach ($categories as $key => $val) {
                $output .= '<div class="col-md-6 project_item" data-id =' . $val['order_num'] . '>';
                $output .= '<a href="' . Url::to(['product-category/view', 'page_slug' => 'product-category', 'slug' => $val['slug'], 'id' => $val['id']]) . '">';
                $output .= '<img class="img-responsive" src="' . yii::getAlias('@web') . $val['image'] . '" alt="' . $val['title'] . '">';
                $output .= '</a>';
                $output .= '<h1 class="text-left bg-white mb-0">';
                $output .= '<a href="' . Url::to(['product-category/view', 'page_slug' => 'product-category', 'slug' => $val['slug'], 'id' => $val['id']]) . '">' . $val['title'] . '</a>';
                $output .= '</h1>';
                $output .= '<p>' . $val['subtitle'] . '</p>';
                $output .= '</div>';
            }

            $result['output'] = $output;
            $result['lastRequestId'] = $categoriesIdArr;
            $result['lastRequestMinId'] = $minId;
            $result['state'] = $state;

            echo json_encode($result);
            die();
        }
    }
}